server:
  port: 8081
  servlet:
        context-path: /
spring:
    application:
        name: marketDEMO
        version: 0.0.1
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: 1234
        url: jdbc:oracle:thin:@//localhost:1521/XE
        username: dydwns
    devtools:
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                default_schema: DYDWNS
                format_sql: true
                show_sql: true
#    mail:
#        host: smtp.gmail.com
#        port: 587
#        properties:
#            mail:
#                smtp:
#                    auth: true
#                    ssl:
#                        trust: smtp.gmail.com
#                    starttls:
#                        enable: true
#                        required: true
#                    timeout: 5000
    security:
        user:
            name: user
            password: 1234
            roles: ADMIN
    servlet:
        multipart:
            location: upload
            max-file-size: 10MB
