server:
    port: 8080
    servlet:
        context-path: /
spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
    application:
      name: marketDEMO
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: 1234
        url: jdbc:oracle:thin:@//localhost:1521/XE
        username: system
    devtools:
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    security:
      user:
        name: user
        password: 1234
        roles: ADMIN
    servlet:
      multipart:
        location: upload
        max-file-size: 10MB
