server:
    port: 8080
    servlet:
        context-path: /
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: marketDEMO
  datasource:
    # 드라이버 클래스 이름 (Oracle Thin Driver)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # 사용자 이름
    username: MARKET_DEV
    # 사용자 암호
    password: MarketDev_1234
    # JDBC URL 형식: jdbc:oracle:thin:@//[IP]:[포트]/[서비스이름]
    url: jdbc:oracle:thin:@//43.201.9.146:1521/xepdb1
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    user:
      name: user
      password: 1234
      roles: ADMIN
  servlet:
    multipart:
      location: upload
      max-file-size: 10MB