server:
    port: 8080
    servlet:
        context-path: /

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: kr.co.team3.product_entity
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    default-statement-timeout: 5

spring:
  main:
    allow-circular-references: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: marketDEMO
  datasource:
    # 드라이버 클래스 이름 (Oracle Thin Driver)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # 사용자 이름
    username: MARKET_DEV
    # 사용자 암호
    password: MarketDev_1234
    # JDBC URL 형식: jdbc:oracle:thin:@//[IP]:[포트]/[서비스이름]
    url: jdbc:oracle:thin:@//43.201.9.146:1521/XEPDB1
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      location: upload
      max-file-size: 10MB
  security:
    user:
      name: user
      password: 1234
      roles: ADMIN
  oauth2:
    client:
      registration:
        google:
          client-id: YOUR_GOOGLE_CLIENT_ID
          client-secret: YOUR_GOOGLE_CLIENT_SECRET
          scope:
            - email
            - profile
        naver:
          client-id: YOUR_NAVER_CLIENT_ID
          client-secret: YOUR_NAVER_CLIENT_SECRET
          scope:
            - name
            - email
          client-name: Naver
        kakao:
          client-id: YOUR_KAKAO_CLIENT_ID
          client-secret: YOUR_KAKAO_CLIENT_SECRET
          scope:
            - profile_nickname
            - account_email
          client-name: Kakao
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
  mail:
    host: smtp.gmail.com
    port: 587
    username: c5092ms@gmail.com
    password: kgwfthgqwlqgmwsg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true